// Generated by CoffeeScript 1.12.5
var CommitsGraph, CommitsGraphMixin, React;
var createReactClass = require('create-react-class');

React = require('react');

CommitsGraphMixin = require('./commits-graph-mixin');

CommitsGraph = React.createClass({
  displayName: 'CommitsGraph',
  mixins: [CommitsGraphMixin],
  render: function() {
    return this.renderGraph();
  }
});

module.exports = CommitsGraph;
